### ISSUE TITLE
Issue_loji

### ISSUE THREAD

**Issue by javiloji** [AraceliRuz/codigo#10]
do {
			try {
				opcion = mostrarMenu(dato);

				recogerOpcion(dato, Javier, opcion);
			} catch (IOException ex) {
				Logger.getLogger(TestCCuenta.class.getName()).log(Level.SEVERE,
						null, ex);
			}
		} while (opcion != 3);

**Comment by AraceliRuz** [comment]
¿Qué le pasa a ese código?
No has hecho referencia a la línea en concreto

**Comment by javiloji** [comment]
Lo siento, la verdad es que no sabía hacerlo.
